### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by FayasNoushad** [sentinm/Store-Bot#1]
Why cloned @AbirHasan2005's Repo?

**Comment by sentinm** [comment]
For my use, that's not a problem for you

**Comment by FayasNoushad** [comment]
Not my problem but please change visibility to private

**Comment by sentinm** [comment]
> Why cloned @AbirHasan2005's Repo?

I forked it but I can't private it to set vars cz it's a fork, so I enables template in my fork and templated it then deleted fork that's all

**Comment by sentinm** [comment]
Owh shit sorry sar, ai thought you are trying to tell me as a kanger now I saw itvs not private, thank tou sir for notifying

**Comment by FayasNoushad** [comment]
Hmm

**Comment by sentinm** [comment]
No I donvt think so, ha. You noted it as copyright
